### ISSUE TITLE
run android 12L

### ISSUE THREAD

**Issue by bmsi77** [royalgraphx/SideswipeOnQEMU#3]
can i run other android version on this platform

**Comment by royalgraphx** [comment]
it already works, currently the bleeding_edge branch doesn't build yet, but its already there

**Comment by bmsi77** [comment]
tnx i test bliss os 14.3 and work prefect but bliss os 14.10 and bliss os 15 not working and have boot loop

**Comment by royalgraphx** [comment]
ill add proper support over the coming weeks, ive been busy with daily work

**Comment by bmsi77** [comment]
tnx
